services:
  api:
    image: api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - database
      - cache
    environment:
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING:-Server=database;Port=5432;Database=dev_db;User Id=dev_user;Password=dev_password;}
      - ConnectionStrings__Cache=${CACHE_CONNECTION_STRING:-cache:6379}
    restart: unless-stopped

  database:
    image: postgres:18.0-alpine3.22
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-dev_db}
      POSTGRES_USER: ${POSTGRES_USER:-dev_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dev_password}
    volumes:
      - db_data:/var/lib/postgresql/data
    # ports:
    #  - "5432:5432"
    restart: unless-stopped

  cache:
    image: valkey/valkey:8.1.4-alpine3.22
    # ports:
    #   - "6379:6379"
    restart: unless-stopped
    
volumes:
  db_data:
    driver: local