@baseUrl = 
@contentType = application/json

###########################################################################################################################################################################################
### Request: POST /api/users/login
### Summary: Uwierzytelnianie użytkownika. Wymaga loginu i hasła. Token JWT oraz refresh token w odpowiedzi.
### Description: Autoryzuje użytkownika na podstawie loginu i hasła. Zwraca token JWT oraz refresh token przy poprawnych danych. W przypadku błędnych danych zwraca odpowiedni kod błędu.
###########################################################################################################################################################################################


POST {{baseUrl}}/api/users/login
Content-Type: {{contentType}}

{
  "login": "login",
  "password": "password"
}

