{
 "title": "Api",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Ogolne", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  { "title": "Zapytania", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 16, "w": 7, "x": 0, "y": 9 },
   "targets": [
    { "limit": 200, "service": "api" }
   ]
  },
  {
   "title": "Ilosc zapytan",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 7, "x": 7, "y": 9 },
   "targets": [
    {
     "expr": "http_server_request_duration_seconds_count",
     "legendFormat": "/{{http_route}}"
    }
   ]
  },
  {
   "title": "5%",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 10, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "p95" ] } },
   "targets": [
    {
     "expr": "http_server_request_duration_seconds_sum",
     "legendFormat": "{{http_request_method}} /{{http_route}} - {{http_response_status_code}}"
    }
   ]
  }
 ]
}